config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'
  get 'about', to: 'pages#about'

  #articles
  resources :articles

  post 'signup', to: 'users#create'
  resources :users, except: [:new]
  post '/auth/login', to: 'authentication#create'

  resources :friendships, only: [:destroy]
  post 'friendships/:id', to: 'friendships#create'
  get 'showFollowers/:id', to: 'friendships#showFollowers'
  get 'showFollowing/:id', to: 'friendships#showFollowing'

  get 'userSearch', to: 'operations#userSearch'
  get 'articleSearch', to: 'operations#articleSearch'
  get 'topicSearch', to: 'operations#searchTopic'
  get 'topArticles', to: 'operations#topArticles'
  get 'similarArticles', to: 'operations#similarArticles'
  get 'listTopic', to: 'operations#listTopic'
  get 'recommendedArticles/:id', to: 'operations#recommendedArticles'
  get 'showArticle', to: 'operations#showArticle'
  get 'sortByLike', to: 'operations#sortByLike'
  get 'sortByComment', to: 'operations#sortByComment'

  resources :comments, only: [:create, :update, :destroy, :show]
  post 'likes/:id', to: 'likes#create'

  post '/articles/viewed/:id', to: 'viewedarticles#create'

  get 'revision', to: 'revisions#show'
  get 'revision/:id', to: 'revisions#replace'

  resources :drafts, only: [:show, :index, :create, :update, :destroy]

  resources :lists, only: [:show, :index, :create, :update, :destroy]
  resources :listitems, only: [:create, :destroy]
  post 'listShare', to: 'lists#listShare'

  resources :saveforlaters, only: [:destroy, :index]
  post 'saveforlaters/:id', to: 'saveforlaters#create'

  post 'payments', to: 'payments#create'
  post 'verify_payment', to: 'payments#verify_payment'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_save { self.email = email.downcase}
  has_many :articles
  has_many :comments
  has_many :viewed_articles
  has_many :subscriptions
  has_many :lists, dependent: :destroy
  has_many :save_for_laters
  has_many :revisions
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum:1 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
  uniqueness: { case_sensitive: false },
  length: { maximum:105 },
  format: { with: VALID_EMAIL_REGEX }
  has_many :active_friendships, class_name:"Friendship", foreign_key:"follower_id", dependent: :destroy
  has_many :passive_friendships, class_name:"Friendship", foreign_key:"followed_id", dependent: :destroy
  has_many :following, through: :active_friendships, source: :followed
  has_many :followers, through: :passive_friendships, source: :follower
  # user1.follow(user2)
  # user2.followers.include?(user1)
  def follow(user)
    active_friendships.create(followed_id: user.id)
  end
  def unfollow(user)
    active_friendships.find_by(followed_id: user.id).destroy
  end
  def following?(user)
    following.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :require_authentication, except: :create

  def create
    @user = User.new(params.require(:user).permit(:username, :email, :password_digest))
    if @user.save
      payload = {
        user_id: @user.id,
        exp: Time.now.to_i + 3600*24
      }
      token = JWT.encode(payload, 'your_secret_key', 'HS256')
      render json: {user: @user, token: token}, status: :created
    else
      render json: @user.errors.full_messages, status: :unprocessable_entity
    end
  end

  def show
    @user=User.find(params[:id])
    @articles=@user.articles
    @followers=Friendship.where(followed_id:@user.id)
    @followings=Friendship.where(follower_id:@user.id)
    render json:{user:@user,articles:@articles,followers:@followers,followings:@followings}, status: :ok
  end

  def update
    @user = User.find(params[:id])
    if @user != @current_user
      return render json: {msg: "you are not author"}, status: :unauthorized
    end
    if @user.update(params.require(:user).permit(:username, :email, :password_digest))
      render json:@user, status: :ok
    else
      render json: {error: @user.errors.full_messages}, status: :unprocessable_entity
    end
  end

  def index
    @users=User.all
    render json:@users,status: :ok
  end

  def destroy
    @user = User.find(params[:id])
    if @user != @current_user
      return render json: {msg: "you are not author"}, status: :unauthorized
    end
    if @user.destroy
      render json: {msg: "given user deleted succesfully"}, status: :ok
    else
      render json: {errors: @user.errors.full_messages}, status: :no_content
    end
  end

  private

  def require_authentication
    header = request.headers['Authorization']
    token = header.split(' ').last if header
    begin
      decoded_token = JWT.decode(token, 'your_secret_key', true, algorithm: 'HS256')
      render json: {error: "invalid token"} if !decoded_token[0]['user_id']
      @current_user = User.find(decoded_token[0]['user_id'])
    rescue JWT::DecodeError
      render json: { error: header }, status: :unauthorized
    end
  end

end

app/views/users/edit.html.erb
<% if @user.errors.any? %>
<% @user.errors.full_messages.each do |msg| %>
  <h2>Errors :</h2>
  <%= msg %>
<% end %>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <p>
  <%= f.label :username %><br>
  <%= f.text_field :username %>
  </p>
  <p>
  <%= f.label :email %><br>
  <%= f.email_field :email %>
  </p>
  <p>
  <%= f.label :password_digest %><br>
  <%= f.password_field :password_digest %>
  </p>
    <p>
    <%= f.submit "Update User" %>
    </p>
<% end %>
<%= link_to 'Go back to users page', users_path %>

app/views/users/index.html.erb
<table>
<thead>
<tr>
<th>Username by:</th>
<th>Email</th>
<th>Password</th>
<th>Article count</th>
<th colspan="3">Actions</th>
<th>Joined</th>
</tr>
</thead>
<tbody>
<% @users.each do |user| %>
<tr>
<td><%= user.username %></td>
<td><%= user.email%></td>
<td><%= user.password_digest %></td>
<td><%= pluralize(user.articles.count,"article") %></td>
<td><%= link_to 'Show', user_path(user) %></td>
<% if logged_in? && user == current_user %>
<td><%= link_to 'Edit', edit_user_path(user) %></td>
<td><%= link_to 'Delete', user_path(user),
data: { turbo_method: :delete }%></td>
<% end %>
<td><%= time_ago_in_words(user.created_at) %> ago</td>
</tr>
<% end %>
</tbody>
</table>
<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false %>
  </div>
<%= link_to 'Create new user', signup_path %>
<%= link_to 'Go back to home page', root_path %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
<% @user.errors.full_messages.each do |msg| %>
  <h2>Errors :</h2>
  <%= msg %>
<% end %>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
    <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
    </p>
    <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
    </p>
    <p>
    <%= f.label :password_digest %><br>
    <%= f.password_field :password_digest %>
    </p>
    <p>
    <%= f.submit %>
    </p>
<% end %>
<%= link_to 'Go back to users page', users_path %>

app/views/users/show.html.erb
<p> Profile of:<%= @user.username %></p>
<p>Email:<%= @user.email %></p>
<p>Password:<%= @user.password_digest %></p>
<%= link_to 'Edit', edit_user_path(@user.id) %>
<%= link_to 'Delete', user_path(@user),
data: { turbo_method: :delete } %>
<h3>Articles by <%= @user.username %></h3>
<table>
<thead>
<tr>
<th>Artcle by:</th>
<th>Title</th>
<th>Description</th>
<th colspan="3">Actions</th>
</tr>
</thead>
<tbody>
<% @articles.each do |article| %>
<tr>
<td><%= article.user.username %></td>
<td><%= article.title %></td>
<td><%= article.description %></td>
<td><%= link_to 'Show', article_path(article) %></td>
<% if logged_in? && article.user == current_user %>
<td><%= link_to 'Edit', edit_article_path(article) %></td>
<td><%= link_to 'Delete', article_path(article),
data: { turbo_method: :delete }%></td></tr>
<% end %>
<% end %>
</tbody>
</table>
<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
  </div>
<%= link_to 'Return to user listing', users_path %>